name       : castor
version    : 1
release    : 1
source     :
    - git|https://git.sr.ht/~julienxx/castor : master
license    :
    - ISC
component  : system.utils
networking : yes
summary    : A Browser for the small internet (Gemini, Gopher, Finger)
description: |
    A graphical client for plain-text protocols written in Rust with GTK. 
    It currently supports the Gemini, Gopher and Finger protocols.
builddeps  :
    - pkgconfig(atk)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(pango)
    - cargo
setup      : |
    %patch -p1 < $pkgfiles/castor-0.7.0-makefile.patch
build      : |
    %make
install    : |
    %make_install
