name       : hid-nintendo
version    : 2.0
release    : 1
homepage   : https://github.com/nicman23/dkms-hid-nintendo
source     :
    - https://github.com/nicman23/dkms-hid-nintendo/archive/2.0.tar.gz : 86792ae53732f70730a282ca56443cd95c3d216f167a95bb07affe689a82b709
license    : GPL-2.0-or-later
summary    : A kernel driver for the Nintendo Switch Pro Controllers and the Joy-Cons.
description: |
    A kernel driver for the Nintendo Switch Pro Controllers and the Joy-Cons.
builddeps  :
    - linux-current
    - linux-current-headers
patterns   :
    - current : /lib/modules/*.current
setup      : |
    pushd ..
    cp -a dkms-hid-nintendo-%version% current-build
build      : |
    pushd current-build
    KERNEL_VERSION="%kernel_version_current%"
    %make -C /lib/modules/${KERNEL_VERSION}/build M=`pwd`/src
install    : |
    pushd current-build
    KERNEL_VERSION="%kernel_version_current%"
    install -D -m 755 src/hid-nintendo.ko $installdir/lib/modules/${KERNEL_VERSION}/kernel/drivers/hid/hid-nintendo.ko
