name       : hid-nintendo
version    : 2.0
release    : 1
homepage   : https://github.com/nicman23/dkms-hid-nintendo
source     :
    - git|https://github.com/nicman23/dkms-hid-nintendo.git : master
license    : GPL-2.0-or-later
summary    : A kernel driver for the Nintendo Switch Pro Controllers and the Joy-Cons.
description: |
    A kernel driver for the Nintendo Switch Pro Controllers and the Joy-Cons.
builddeps  :
    - linux-current
    - linux-current-headers
setup      : |
build      : |
    KERNEL_VERSION="%kernel_version_current%"
    %make -C /lib/modules/${KERNEL_VERSION}/build M=`pwd`/src
install    : |
    KERNEL_VERSION="%kernel_version_current%"
    install -D -m 755 src/hid-nintendo.ko $installdir/lib/modules/${KERNEL_VERSION}/kernel/drivers/hid/hid-nintendo.ko
