#!/usr/bin/fish

function buildme
    echo Now building (basename $argv)
    cd $argv
    sudo solbuild build package.yml -p local-unstable-x86_64 -d
    sudo rm /var/lib/solbuild/local/(basename $argv)*.eopkg
    sudo mv *.eopkg /var/lib/solbuild/local
    cd ..
end

cd (dirname (realpath (status -f)))

if test "$argv"
    for i in $argv
        buildme $i
    end
else
    sudo rm /var/lib/solbuild/local/*.eopkg
    ./build (ls -d */)
end

sudo mv (fd -e eopkg) /var/lib/solbuild/local/
cd /var/lib/solbuild/local/
sudo eopkg index --skip-signing /var/lib/solbuild/local/
sudo eopkg ur
