#!/usr/bin/fish
set profile "-punstable-x86_64"

function buildme
    echo Now building (basename $argv)
    cd $argv
    sudo solbuild build package.yml -d $profile
    sudo eopkg it --reinstall (basename $argv)*.eopkg
    cd ..
end

cd (dirname (realpath (status -f)))

sudo solbuild init $profile
sudo solbuild update $profile

if test "$argv"
    for i in $argv
        buildme $i
    end
else
    sudo ./build (cat list)
end
