#!/usr/bin/fish
function buildme
    echo Now building (basename $argv)
    cd $argv
    make
    sudo eopkg it --reinstall (basename $argv)*.eopkg
    cd ..
end

cd (dirname (realpath (status -f)))

set profile "-punstable-x86_64"
sudo solbuild init $profile
sudo solbuild update $profile

if test "$argv"
    for i in $argv
        buildme $i
    end
else
    sudo ./build (cat list)
end
