name       : webp-pixbuf-loader
version    : 1
release    : 1
source     :
    - git|https://github.com/aruiz/webp-pixbuf-loader.git : master
license    : GPL-2.0-or-later
summary    : Insert summary here
description: |
    Insert description here
builddeps  :
    - pkgconfig(libwebp)
    - pkgconfig(gdk-pixbuf-2.0)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
