name       : webp-pixbuf-loader
version    : 0.0.5
release    : 1
source     :
  - https://github.com/aruiz/webp-pixbuf-loader/archive/refs/tags/0.0.5.tar.gz : 8271af4dd3d49792dfd157031d44997187a31e039f7b7b264bc9dded17f24cb9
license    : LGPL-2.0-or-later
summary    : WebP GDK Pixbuf Loader library
description: |
  WebP Image format GdkPixbuf loader
builddeps  :
  - pkgconfig(libwebp)
  - pkgconfig(gdk-pixbuf-2.0)
setup      : |
  %meson_configure
build      : |
  %ninja_build
install    : |
  %ninja_install
