name       : starship
version    : 0.44.0
release    : 1
source     :
    - git|https://github.com/starship/starship.git : master
license    :
    - ISC
component  : system.utils
networking : yes
summary    : The minimal, blazing-fast, and infinitely customizable prompt for any shell!
description: |
    The minimal, blazing-fast, and infinitely customizable prompt for any shell!

    Fast: it's fast – really really fast! rocket
    Customizable: configure every aspect of your prompt.
    Universal: works on any shell, on any operating system.
    Intelligent: shows relevant information at a glance.
    Feature rich: support for all your favorite tools.
    Easy: quick to install – start using it in minutes.
builddeps  :
    - cargo
build      : |
    cargo build --release
install    : |
    install -Dm00755 target/release/starship $installdir/usr/bin/starship
