name       : dwarfs
version    : 0.4.0
release    : 2
source     :
    - https://github.com/mhx/dwarfs/releases/download/v0.4.0/dwarfs-0.4.0.tar.bz2 : 1244068aa228d4240342566ce66b3cd0b51bf1a91726d71a9c222d6066b7ea31
license    : GPL-3.0-or-later
networking : yes
summary    : A fast high compression read-only file system
description: DwarFS is a read-only file system with a focus on achieving very high compression ratios in particular for very redundant data.
builddeps  :
    - double-conversion-devel
    - fuse-devel
    - fmt-devel
    - gflags-devel
    - glog-devel
    - jemalloc-devel
    - libarchive-devel
    - libboost-devel
    - libevent-devel
    - lz4-devel
    - ruby-devel
    - sparsehash
    - xxhash-devel
    - zstd-devel
setup      : |
    PATH="$(ruby -r rubygems -e 'puts Gem.user_dir')/bin:$PATH"
    gem install --user-install ronn
    %cmake -DPREFER_SYSTEM_ZSTD=1 -DPREFER_SYSTEM_XXHASH=1
build      : |
    %make
install    : |
    %make_install
