name       : tabbed
version    : 1
release    : 1
source     :
    - git|git://git.suckless.org/tabbed : master
license    : GPL-2.0-or-later
summary    : Insert summary here
description: |
    Insert description here
builddeps  :
    - pkgconfig(xft)
rundeps    :
    - devil
build      : |
    %make
install    : |
    %make_install PREFIX=%PREFIX%
