name       : ddccontrol
version    : 1
release    : 1
source     :
    - git|https://github.com/ddccontrol/ddccontrol.git : master
license    : GPL-2.0-or-later
summary    : Insert summary here
description: |
    Insert description here
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libpci)
rundeps    :
    - pciutils
setup      : |
    ./autogen.sh
    %configure --sysconfdir=/etc
build      : |
    %make
install    : |
    %make_install
