name       : links-x11
version    : 2.20.2
release    : 12
source     :
    - http://links.twibright.com/download/links-2.20.2.tar.bz2 : 4b4f07d0e6261118d1365a5a5bfa31e1eafdbd280cfae6f0e9eedfea51a2f424
license    : GPL-2.0-or-later
component  : network.web.browser
summary    : A text WWW browser
description: |
    A text WWW browser, similar to Lynx
builddeps  :
    - pkgconfig(libevent)
    - pkgconfig(libpng)
    - pkgconfig(libzstd)
    - pkgconfig(x11)
    - pkgconfig(xt)
    - bzip2-devel
    - gpm-devel
    - librsvg-devel
setup      : |
    %patch -p1 < $pkgfiles/*.patch
    %configure --enable-graphics --with-x --with-fb --x-includes=/usr/include/X11/ --x-libraries=/usr/lib64/X11/
build      : |
    %make
install    : |
    %make_install
