name       : bzip3
version    : 1.1.5
release    : 1
source     :
    - https://github.com/kspalaiologos/bzip3/releases/download/1.1.5/bzip3-1.1.5.tar.zst : e2e5199cb73a3b5ad670260bbb01161c7954ef3330203c0a1adf3eb81a71398d
license    : LGPL-3.0-or-later
summary    : A better and stronger spiritual successor to BZip2.
description: A better, faster and stronger spiritual successor to BZip2. Features 
    higher compression ratios and better performance thanks to a order-0 context 
    mixing entropy coder, a fast Burrows-Wheeler transform code making use of suffix
    arrays and a RLE with Lempel Ziv+Prediction pass based on LZ77-style string
    matching and PPM-style context modeling.
optimize   : speed
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
