name       : libjxl
version    : 0.6
release    : 1
source     :
  - git|https://github.com/libjxl/libjxl.git : cdd3ae6ca12ae3961f8c2118d10636ee091ca40b
license    : BSD-3-Clause
summary    : JPEG XL image format reference implementation
description: JPEG XL (.jxl) is the next-generation, general-purpose image compression codec by the JPEG committee. 
builddeps  :
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(libpng)
    - pkgconfig(libbrotlicommon)
    - pkgconfig(gimp-2.0)
setup      : |
    %cmake -DBUILD_TESTING=OFF -DJPEGXL_ENABLE_PLUGINS=true
build      : |
    %make
install    : |
    %make_install
