name       : melonds
version    : 1
release    : 1
source     :
    - git|https://github.com/Arisotura/melonDS : master
license    : GPL-2.0-or-later
summary    : Insert summary here
description: |
    Insert description here
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(sdl2)
setup      : |
    %cmake
build      : |
    %make
install    : |
    %make_install
