name       : ninfs
version    : 1
release    : 1
source     :
    - git|https://github.com/ihaveamac/ninfs.git : 2.0
license    : GPL-2.0-or-later
summary    : Insert summary here
description: |
    Insert description here
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
