name       : rom-properties
version    : 1.8.3
release    : 2
source     :
  - git|https://github.com/GerbilSoft/rom-properties.git : master
license    : GPL2
summary    : This shell extension adds a few nice features to file browsers for managing video game ROM and disc images
description: This shell extension adds a few nice features to file browsers for managing video game ROM and disc images
builddeps  :
    - curl-devel
    - libseccomp-devel
    - libnettle-devel
    - nautilus-extension-devel
    - caja-extensions-devel
    - caja-devel
    - gsound-devel
    - libcairo-devel
    - libgtk-2-devel
    - libgtk-3-devel
setup      : |
    %cmake
build      : |
    %make
install    : |
    %make_install
    install -Ddm 00755 $installdir/etc/apparmor.d/local
    touch $installdir/etc/apparmor.d/local/usr.bin.rpcli
