name       : rom-properties
version    : 1.8.3
release    : 2
source     :
    - https://github.com/GerbilSoft/rom-properties/archive/refs/tags/v1.8.3.tar.gz : 72bbf5560f197a7a53cf2686e23e204027bf3fbbc5ef733f4194ec3c582e61c4
license    : GPL2
summary    : This shell extension adds a few nice features to file browsers for managing video game ROM and disc images
description: This shell extension adds a few nice features to file browsers for managing video game ROM and disc images
builddeps  :
    - curl-devel
    - caja-devel
    - libseccomp-devel
    - libnettle-devel
setup      : |
    %cmake
build      : |
    %make
install    : |
    %make_install
    install -Ddm 00755 $installdir/etc/apparmor.d/local
    touch $installdir/etc/apparmor.d/local/usr.bin.rpcli
