name       : zerotier
version    : 1
release    : 1
source     :
    - git|https://github.com/zerotier/ZeroTierOne.git : master
license    : GPL-2.0-or-later
summary    : Insert summary here
description: |
    Insert description here
build      : |
    %make
install    : |
    %make_install
