name       : nextdns
version    : 1
release    : 1
source     :
    - git|https://github.com/nextdns/nextdns.git : master
license    : GPL-2.0-or-later
summary    : Insert summary here
networking : yes
description: |
    Insert description here
builddeps  :
    - golang
build      : |
    go build
install    : |
    install -Dm00755 nextdns $installdir/usr/bin/nextdns
