name       : joycond
version    : 0.3.0
release    : 1
source     :
    - git|https://github.com/DanielOgorchock/joycond.git : master
license    : GPL-3.0-or-later
summary    : joycond is a linux daemon which uses the evdev devices provided by hid-nintendo
    (formerly known as hid-joycon) to implement joycon pairing.
description: |
    joycond is a linux daemon which uses the evdev devices provided by hid-nintendo (formerly known as hid-joycon) to implement joycon pairing.
builddeps  :
    - pkgconfig(libevdev)
setup      : |
    %cmake
build      : |
    %make
install    : |
    %make_install

    # Enable by default, users can disable now with systemctl mask tlp
    install -Ddm 00755 $installdir/etc/systemd/system/multi-user.target.wants
    ln -sv ../joycond.service $installdir/etc/systemd/system/multi-user.target.wants
