name       : oxipng
version    : 3.0.0
release    : 1
source     :
    - git|https://github.com/shssoichiro/oxipng.git : master
license    :
    - MIT
component  : system.utils
networking : yes
summary    : Multithreaded PNG optimizer written in Rust
description: |
    Oxipng is a multithreaded lossless PNG compression optimizer. It can be used via a command-line interface or as a library in other Rust programs.
builddeps  :
    - cargo
build      : |
    cargo build --release
install    : |
    install -Dm00755 target/release/oxipng $installdir/usr/bin/oxipng
check      : |
    cargo test --all
