name       : earlyoom
version    : 1
release    : 1
source     :
    - git|https://github.com/rfjakob/earlyoom.git : master
license    : GPL-2.0-or-later
summary    : Insert summary here
description: |
    Insert description here
build      : |
    %make PREFIX=%PREFIX% SYSTEMDUNITDIR=%libdir%/systemd/system earlyoom
install    : |
    %make_install PREFIX=%PREFIX% SYSTEMDUNITDIR=%libdir%/systemd/system earlyoom
