name       : interception-tools
version    : 1
release    : 1
source     :
    - git|https://gitlab.com/interception/linux/tools.git : master
license    : GPL-2.0-or-later
summary    : Insert summary here
description: |
    Insert description here
builddeps  :
    - pkgconfig(libevdev)
    - pkgconfig(libudev)
    - pkgconfig(yaml-cpp)
setup      : |
    %cmake
build      : |
    %make
install    : |
    %make_install
