name       : bcml
version    : 1
release    : 1
source     :
    - https://github.com/NiceneNerd/BCML/archive/v3.0.0b18.tar.gz : 5ee09ad49e3b21b24ba56108f96dbc5574c4a3defe1772e969e994a1538c7530
license    : GPL-2.0-or-later
summary    : Insert summary here
description: |
    Insert description here
networking : yes
builddeps  :
    - pkgconfig(yaml-0.1)
    - nodejs
    - pyyaml
    - python-xxhash
    - python-wheel
    - python-requests
setup      : |
    pushd bcml/assets
    npm install
    ! timeout 5s npm test
    pushd ../..
build      : |
    %python3_setup
install    : |
    %python3_install
    cat <<EOF > $installdir/usr/bin/bcml
    #!/bin/bash
    python3 -m bcml
    EOF
